### ISSUE TITLE
Incorrect matches for httpjunk:// URIs

### ISSUE THREAD

**Issue by Qix-** [Kikobeats/is-url-http#1]
Need to add a colon at the end of the scheme regex.

The following URLs will generate false positives given the current implementation.

```
httpsucks://lol.wtf
http'DROP TABLE users;--
```

**Comment by Qix-** [comment]
Also,

> Check if an URL is a valid HTTP URL.

I believe this to be misleading. Even if you add the `:` to the end, you're still going to face the issue of junk (e.g. `'http:!!!\0'`) being accepted as "valid".

This is specifically what the URL library built into Node is for, which I recommend using instead - perhaps using it and returning a boolean would be more security-conscious and correct anyway.

**Comment by Kikobeats** [comment]
> The following URLs will generate false positives given the current implementation.

Should be easy to handle just modifying the regex to be more restricted.

> I believe this to be misleading.

That's true; The idea of the library is to check if an input looks like an URL, then you can try to ping it, that it's, in fact, the only way to be sure it's an URL and accessible (out of the scope).
