### ISSUE TITLE
Provide a Typescript type declaration

### ISSUE THREAD

**Issue by khalyomede** [Kikobeats/is-url-http#4]
It would be great to activate type checking using Typescript via your declaration file :)

**Comment by Kikobeats** [comment]
I'm not a TypeScript regular user, if anybody is interested in this I'm happy to accept a PR 🙂

**Comment by geopic** [comment]
I'll be happy to write one @Kikobeats 😄

**Comment by Kikobeats** [comment]
@geopic please do it!

**Comment by geopic** [comment]
Good stuff, I'll get started on it soon.
